#!/bin/sh

PROJECT=`docker exec php-api-container php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Errors && PHP-CS-Fixer fix the file"
for FILE in $SFILES
do
    docker exec php-api-container /var/www/html/vendor/bin/php-cs-fixer fix $PROJECT/$FILE --rules=@Symfony,@PSR2,-no_superfluous_phpdoc_tags
    docker exec php-api-container php -l -d display_errors=0 $PROJECT/$FILE

    git add $FILE

    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

exit $?
